FROM node:14

WORKDIR /workspace

COPY ./package.json ./
RUN npm install
COPY . ./

EXPOSE 3000

CMD [ "npm", "run", "start:dev" ]

#### Considering that we are in the current directory

### Build image
## docker build -t dev.todo.api .
# -t: the target is the name of the image,
# we will refere it when run it the container

### Run container 
## docker run -p 3000:3000 -v $PWD:/workspace --name dev.todo.api dev.todo.api
# -d: detachable mode
# -p: port mapping
# -v: volume mapping
# --name: the name of the container
# at last i specified the image name to run the container